version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=saas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  api:
    build: ./api
    restart: unless-stopped
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./api:/api/
    depends_on:
      - postgres
      - redis

  company-client:
    build: ./company-client
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080

  driver-client:
    build: ./driver-client
    restart: unless-stopped
    tty: true
    ports:
      - 8081:8081

  socket.io:
    build: ./socket.io
    restart: unless-stopped
    tty: true
    ports:
      - 6001:6001

volumes:
  postgresql-data:
    driver: local